#!/bin/sh
### BEGIN INIT INFO
# Provides:          zabbix-agent
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start zabbix-agent daemon
### END INIT INFO

NAME=zabbix_agentd
DAEMON=/usr/sbin/${NAME}
DESC="Zabbix agent daemon"
PIDFILE=/tmp/$NAME.pid

export PATH=/bin:/sbin

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting zabbix-agent…' >&2
	$DAEMON -c /etc/zabbix_agentd.conf
  echo 'Service started' >&2
}	

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping zabbix-agent…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

save() {

	./bin/zabbix_conf_save

}

uninstall() {

	stop

}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
	
status)
      if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) ; then
         echo "zabbix-agent is running"
         exit 0
      else
         echo "zabbix-agent is not running"
         exit 3
      fi
	;;
	
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|save|}"
esac
